In [1]:
# 1. Conectarse a la url que contiene el archivo CSV de medallas olímpicas.


import pandas as pd
import sqlite3

medals=pd.read_csv('C:/Data-Engineer-Prisma/Unidad20/contenido/medals.csv',encoding = "utf-8")

In [2]:
# 2. Descargar los datos y obtener un sub dataset que contenga a todas las 
# medallas de oro (Gold) Estados Unidos (USA) a partir delaño 1950.


usa_champions = medals[(medals["Year"] > 1950) & (medals["Medal"] == "Gold") & (medals["NOC"] == "USA")]
usa_champions

,Year,City,Sport,Discipline,NOC,Event,Event gender,Medal
311,1952,Oslo,Skating,Figure skating,USA,individual,M,Gold
314,1952,Oslo,Skating,Speed skating,USA,500m,M,Gold
316,1952,Oslo,Skiing,Alpine Skiing,USA,giant slalom,W,Gold
317,1952,Oslo,Skiing,Alpine Skiing,USA,slalom,W,Gold
386,1956,Cortina d'Ampezzo,Skating,Figure skating,USA,individual,M,Gold
...,...,...,...,...,...,...,...,...
2301,2006,Turin,Skiing,Alpine Skiing,USA,Alpine combined,M,Gold
2302,2006,Turin,Skiing,Alpine Skiing,USA,giant slalom,W,Gold
2305,2006,Turin,Skiing,Snowboard,USA,Half-pipe,M,Gold
2307,2006,Turin,Skiing,Snowboard,USA,Half-pipe,W,Gold
2309,2006,Turin,Skiing,Snowboard,USA,Snowboard Cross,M,Gold

In [3]:
# 3. Crear una base de datos “olympics” en SQLite y la tabla “medals"


conn = sqlite3.connect('olympics.db')

cursor = conn.cursor()

query = """Create Table If Not Exists medals(
                                    Year Integer,
                                    City Text,
                                    Sport Text,
                                    Discipline Text,
                                    NOC Text,
                                    Event Text,
                                    Event_gender Text,
                                    Medal Text
                                    );"""

cursor.execute(query)
conn.commit()

In [4]:
# 4. Guardar en la base de datos. los datos generados en el sub dataset.


data = list(usa_champions.itertuples(index=False, name=None))
cursor.executemany("Insert Into medals Values (?, ?, ?, ?, ?, ?, ?, ?)", data)
conn.commit()

In [5]:
# 5. Consultar la base de datos y validar que los datos se hayan cargado correctamente.


query = "Select * From medals Limit 20"
cursor.execute(query)
results = cursor.fetchall()

for r in results:
    print(r)
    
conn.close()

(1952, 'Oslo', 'Skating', 'Figure skating', 'USA', 'individual', 'M', 'Gold')
(1952, 'Oslo', 'Skating', 'Speed skating', 'USA', '500m', 'M', 'Gold')
(1952, 'Oslo', 'Skiing', 'Alpine Skiing', 'USA', 'giant slalom', 'W', 'Gold')
(1952, 'Oslo', 'Skiing', 'Alpine Skiing', 'USA', 'slalom', 'W', 'Gold')
(1956, "Cortina d'Ampezzo", 'Skating', 'Figure skating', 'USA', 'individual', 'M', 'Gold')
(1956, "Cortina d'Ampezzo", 'Skating', 'Figure skating', 'USA', 'individual', 'W', 'Gold')
(1960, 'Squaw Valley', 'Ice Hockey', 'Ice Hockey', 'USA', 'ice hockey', 'M', 'Gold')
(1960, 'Squaw Valley', 'Skating', 'Figure skating', 'USA', 'individual', 'M', 'Gold')
(1960, 'Squaw Valley', 'Skating', 'Figure skating', 'USA', 'individual', 'W', 'Gold')
(1964, 'Innsbruck', 'Skating', 'Speed skating', 'USA', '500m', 'M', 'Gold')
(1968, 'Grenoble', 'Skating', 'Figure skating', 'USA', 'individual', 'W', 'Gold')
(1972, 'Sapporo', 'Skating', 'Speed skating', 'USA', '1500m', 'W', 'Gold')
(1972, 'Sapporo', 'Skating', 'Speed skating', 'USA', '500m', 'W', 'Gold')
(1972, 'Sapporo', 'Skiing', 'Alpine Skiing', 'USA', 'slalom', 'W', 'Gold')
(1976, 'Innsbruck', 'Skating', 'Figure skating', 'USA', 'individual', 'W', 'Gold')
(1976, 'Innsbruck', 'Skating', 'Speed skating', 'USA', '1000m', 'M', 'Gold')
(1976, 'Innsbruck', 'Skating', 'Speed skating', 'USA', '500m', 'W', 'Gold')
(1980, 'Lake Placid', 'Ice Hockey', 'Ice Hockey', 'USA', 'ice hockey', 'M', 'Gold')
(1980, 'Lake Placid', 'Skating', 'Speed skating', 'USA', '10000m', 'M', 'Gold')
(1980, 'Lake Placid', 'Skating', 'Speed skating', 'USA', '1000m', 'M', 'Gold')